apiVersion: {{ template "artemis.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-autostarter
{{ include "artemis.labels" . | indent 4 }}
  name: {{ .Release.Name }}-autostarter
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-autostarter
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}-autostarter
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: populate-pvc
        image: busybox
        volumeMounts:
        - mountPath: /configmaps
          name: autostarter-configmap
        - mountPath: /pvc
          name: autostarter-pvc
          subPath: configs
        command: ['sh', '-c', 'false | cp -i /configmaps/logging.yaml /pvc/ 2> /dev/null']
      - name: wait-for-rmq
        image: busybox
        command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-{{ .Values.rabbitmqHost }}-svc {{ .Values.rabbitmqPort }}; do echo waiting for services; sleep 10; done;']
      - name: wait-for-pg
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-{{ .Values.dbHost }}-svc {{ .Values.dbPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-database
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-database-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-prefixtree
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-prefixtree-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-configuration
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-configuration-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-fileobserver
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-fileobserver-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-autoignore
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-autoignore-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-notifier
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-notifier-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-detection
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-detection-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-mitigation
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-mitigation-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-riperistap
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-riperistap-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-bgpstreamlivetap
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-bgpstreamlivetap-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-bgpstreamkafkatap
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-bgpstreamkafkatap-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-bgpstreamhisttap
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-bgpstreamhisttap-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-exabgptap
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-exabgptap-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      containers:
      - env:
        - name: AUTO_RECOVER_PROCESS_STATE
          valueFrom:
            configMapKeyRef:
              name: { { .Release.Name } }-configmap
              key: autoRecoverProcessState
        - name: CHECK_INTERVAL
          value: "5"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: dbHost
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: dbName
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: dbPass
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: dbPort
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: dbUser
        - name: REST_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: restPort
        image: inspiregroup/artemis-autostarter:{{ .Values.systemVersion }}
        imagePullPolicy: Always
        name: autostarter
        resources: {}
        volumeMounts:
        - mountPath: /etc/artemis/logging.yaml
          name: autostarter-pvc
          subPath: configs/logging.yaml
      restartPolicy: Always
      volumes:
      - configMap:
          name: {{ .Release.Name }}-volumes
        name: autostarter-configmap
      - persistentVolumeClaim:
          claimName: {{ .Release.Name }}-autostarter-pvc
        name: autostarter-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
status: {}
