apiVersion: {{ template "artemis.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-bgpstreamkafkatap
{{ include "artemis.labels" . | indent 4 }}
  name: {{ .Release.Name }}-bgpstreamkafkatap
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-bgpstreamkafkatap
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}-bgpstreamkafkatap
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: populate-pvc
        image: busybox
        volumeMounts:
        - mountPath: /configmaps
          name: bgpstreamkafkatap-configmap
        - mountPath: /pvc
          name: bgpstreamkafkatap-pvc
          subPath: configs
        command: ['sh', '-c', 'false | cp -i /configmaps/logging.yaml /configmaps/mon-services.conf /pvc/ 2> /dev/null']
      - name: wait-for-rmq
        image: busybox
        command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-{{ .Values.rabbitmqHost }}-svc {{ .Values.rabbitmqPort}}; do echo waiting for services; sleep 10; done;']
      - name: wait-for-redis
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-{{ .Values.redisHost }}-svc {{ .Values.redisPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-prefixtree
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-prefixtree-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      containers:
      - env:
        - name: MON_TIMEOUT_LAST_BGP_UPDATE
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: monTimeoutLastBgpUpdate
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: rabbitmqHost
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: rabbitmqPass
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: rabbitmqPort
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: rabbitmqUser
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: redisHost
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: redisPort
        - name: REST_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: restPort
        image: inspiregroup/artemis-bgpstreamkafkatap:{{ .Values.systemVersion }}
        imagePullPolicy: Always
        name: bgpstreamkafkatap
        resources: {}
        volumeMounts:
        - mountPath: /etc/artemis/logging.yaml
          name: bgpstreamkafkatap-pvc
          subPath: configs/logging.yaml
        - mountPath: /etc/supervisor/conf.d/services.conf
          name: bgpstreamkafkatap-pvc
          subPath: configs/mon-services.conf
      restartPolicy: Always
      volumes:
      - configMap:
          name: {{ .Release.Name }}-volumes
        name: bgpstreamkafkatap-configmap
      - persistentVolumeClaim:
          claimName: {{ .Release.Name }}-bgpstreamkafkatap-pvc
        name: bgpstreamkafkatap-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
status: {}
