apiVersion: {{ template "artemis.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: bgpstreamhisttap
{{ include "artemis.labels" . | indent 4 }}
  name: bgpstreamhisttap
spec:
  selector:
    matchLabels:
      app: bgpstreamhisttap
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bgpstreamhisttap
    spec:
      initContainers:
      - name: wait-for-rmq
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z {{ .Values.rabbitmqHost }} {{ .Values.rabbitmqPort}}; do echo waiting for services; sleep 10; done;']
      - name: wait-for-prefixtree
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z prefixtree {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      containers:
      - env:
        - name: HISTORIC
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: historic
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rabbitmqHost
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: secret
              key: rabbitmqPass
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rabbitmqPort
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rabbitmqUser
        - name: REST_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: restPort
        image: inspiregroup/artemis-bgpstreamhisttap:{{ .Values.systemVersion }}
        imagePullPolicy: IfNotPresent
        name: bgpstreamhisttap
        resources: {}
        volumeMounts:
        - mountPath: /etc/artemis/logging.yaml
          name: bgpstreamhisttap-configmap
          subPath: logging.yaml
      restartPolicy: Always
      volumes:
      - configMap:
          name: volumes
        name: bgpstreamhisttap-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
