apiVersion: {{ template "artemis.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-configuration
{{ include "artemis.labels" . | indent 4 }}
  name: {{ .Release.Name }}-configuration
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-configuration
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}-configuration
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: populate-pvc
        image: busybox
        volumeMounts:
        - mountPath: /configmaps
          name: configuration-configmap
        - mountPath: /pvc
          name: configuration-pvc
          subPath: configs
        command: ['sh', '-c', 'false | cp -i /configmaps/config.yaml /configmaps/logging.yaml /pvc/ 2> /dev/null']
      - name: wait-for-rmq
        image: busybox
        command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-{{ .Values.rabbitmqHost }}-svc {{ .Values.rabbitmqPort }}; do echo waiting for services; sleep 10; done;']
      - name: wait-for-redis
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-{{ .Values.redisHost }}-svc {{ .Values.redisPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-database
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-database-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-prefixtree
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-prefixtree-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-detection
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-detection-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-mitigation
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-mitigation-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-notifier
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-notifier-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-riperistap
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-riperistap-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-bgpstreamlivetap
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-bgpstreamlivetap-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-bgpstreamkafkatap
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-bgpstreamkafkatap-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-bgpstreamhisttap
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-bgpstreamhisttap-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-exabgptap
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-exabgptap-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-autoignore
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-autoignore-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      containers:
      - env:
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: rabbitmqHost
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: rabbitmqPass
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: rabbitmqPort
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: rabbitmqUser
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: redisHost
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: redisPort
        - name: REST_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: restPort
        image: inspiregroup/artemis-configuration:{{ .Values.systemVersion }}
        imagePullPolicy: Always
        name: configuration
        resources: {}
        volumeMounts:
        - mountPath: /etc/artemis/logging.yaml
          name: configuration-pvc
          subPath: configs/logging.yaml
        - mountPath: /etc/artemis/config.yaml
          name: backend-pvc
          subPath: configs/config.yaml
      restartPolicy: Always
      volumes:
      - configMap:
          name: {{ .Release.Name }}-volumes
        name: configuration-configmap
      - persistentVolumeClaim:
          claimName: {{ .Release.Name }}-configuration-pvc
        name: configuration-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
status: {}
