apiVersion: {{ template "artemis.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: configuration
{{ include "artemis.labels" . | indent 4 }}
  name: configuration
spec:
  selector:
    matchLabels:
      app: configuration
  replicas: {{ .Values.services.configuration.replicas | default 1 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: configuration
    spec:
      initContainers:
      - name: wait-for-rmq
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z {{ .Values.rabbitmqHost }} {{ .Values.rabbitmqPort }}; do echo waiting for services; sleep 10; done;']
      - name: wait-for-redis
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z {{ .Values.redisHost }} {{ .Values.redisPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-database
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z database {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-prefixtree
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z prefixtree {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-detection
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z detection {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-mitigation
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z mitigation {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-notifier
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z notifier {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-riperistap
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z riperistap {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-bgpstreamlivetap
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z bgpstreamlivetap {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-bgpstreamkafkatap
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z bgpstreamkafkatap {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-bgpstreamhisttap
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z bgpstreamhisttap {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-exabgptap
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z exabgptap {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-autoignore
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z autoignore {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      containers:
      - env:
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rabbitmqHost
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: secret
              key: rabbitmqPass
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rabbitmqPort
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rabbitmqUser
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: redisHost
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: redisPort
        - name: REST_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: restPort
        image: {{ .Values.services.configuration.image }}:{{ .Values.systemVersion }}
        imagePullPolicy: IfNotPresent
        name: configuration
        resources: {}
        volumeMounts:
        - mountPath: /etc/artemis/
          name: configuration-configmap
      restartPolicy: Always
      volumes:
      - configMap:
          name: volumes
          items:
            - key: config.yaml
              path: config.yaml
            - key: logging.yaml
              path: logging.yaml
        name: configuration-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
