apiVersion: {{ template "artemis.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: detection
{{ include "artemis.labels" . | indent 4 }}
  name: detection
spec:
  selector:
    matchLabels:
      app: detection
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: detection
    spec:
      initContainers:
      - name: wait-for-rmq
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z {{ .Values.rabbitmqHost }} {{ .Values.rabbitmqPort }}; do echo waiting for services; sleep 10; done;']
      - name: wait-for-redis
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z {{ .Values.redisHost }} {{ .Values.redisPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-prefixtree
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z prefixtree {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-database
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z database {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-notifier
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '-c', 'until nc -z notifier {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      containers:
      - env:
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rabbitmqHost
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: secret
              key: rabbitmqPass
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rabbitmqPort
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rabbitmqUser
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: redisHost
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: redisPort
        - name: REST_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: restPort
        - name: RPKI_VALIDATOR_ENABLED
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rpkiValidatorEnabled
        - name: RPKI_VALIDATOR_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rpkiValidatorHost
        - name: RPKI_VALIDATOR_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rpkiValidatorPort
        - name: TEST_ENV
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: testEnv
        image: inspiregroup/artemis-detection:{{ .Values.systemVersion }}
        imagePullPolicy: IfNotPresent
        name: detection
        resources: {}
        volumeMounts:
        - mountPath: /etc/artemis/logging.yaml
          name: detection-configmap
          subPath: logging.yaml
      restartPolicy: Always
      volumes:
      - configMap:
          name: volumes
        name: detection-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
