apiVersion: {{ template "artemis.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-fileobserver
{{ include "artemis.labels" . | indent 4 }}
  name: {{ .Release.Name }}-fileobserver
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fileobserver
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fileobserver
    spec:
      initContainers:
      - name: wait-for-configuration
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-configuration-svc {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      containers:
      - env:
        - name: RELEASE_NAME
          value: {{ .Release.Name }}
        - name: REST_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: restPort
        image: inspiregroup/artemis-fileobserver:{{ .Values.systemVersion }}
        imagePullPolicy: Always
        name: fileobserver
        resources: {}
        volumeMounts:
        - mountPath: /etc/artemis/
          name: fileobserver-configmap
      restartPolicy: Always
      volumes:
      - configMap:
          name: {{ .Release.Name }}-volumes
          items:
          - key: config.yaml
            path: config.yaml
          - key: logging.yaml
            path: logging.yaml
        name: fileobserver-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
