apiVersion: {{ template "artemis.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: frontend
{{ include "artemis.labels" . | indent 4 }}
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
      - name: wait-for-rmq
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z {{ .Values.rabbitmqHost }} {{ .Values.rabbitmqPort }}; do echo waiting for services; sleep 10; done;']
      containers:
      - env:
        - name: ARTEMIS_WEB_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: artemisWebHost
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: apiHost
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: apiPort
        - name: REST_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: restPort
        - name: BIND_IP
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: bindIp
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: dbHost
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: dbPort
        - name: FLASK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: flaskSecret
        - name: HASURA_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: hasuraHost
        - name: HASURA_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: hasuraPort
        - name: JS_VERSION
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: jsVersion
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: jwtSecret
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rabbitmqHost
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: secret
              key: rabbitmqPass
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rabbitmqPort
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rabbitmqUser
        - name: SECURITY_PASSWORD_SALT
          valueFrom:
            secretKeyRef:
              name: secret
              key: passwordSalt
        - name: SYSTEM_VERSION
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: systemVersion
        - name: USER_ROOT_EMAIL
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: adminEmail
        - name: USER_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: adminPass
        - name: USER_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: adminUser
        - name: WEBAPP_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: webappPort
        - name: GUNICORN_WORKERS
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: gunicornWorkers
        image: inspiregroup/artemis-frontend:{{ .Values.systemVersion }}
        imagePullPolicy: IfNotPresent
        name: frontend
        resources: {}
        volumeMounts:
        - mountPath: /etc/artemis/
          name: frontend-configmap
        - mountPath: /etc/webapp/db/
          name: frontend-pvc
          subPath: webbapp-db
      restartPolicy: Always
      volumes:
      - configMap:
          name: volumes
          items:
          - key: webapp.cfg
            path: webapp.cfg
          - key: logging.yaml
            path: logging.yaml
        name: frontend-configmap
      - persistentVolumeClaim:
          claimName: frontend-pvc
        name: frontend-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
