apiVersion: {{ template "artemis.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-mitigation
{{ include "artemis.labels" . | indent 4 }}
  name: {{ .Release.Name }}-mitigation
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mitigation
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mitigation
    spec:
      initContainers:
      - name: wait-for-rmq
        image: busybox
        command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-{{ .Values.rabbitmqHost }} {{ .Values.rabbitmqPort }}; do echo waiting for services; sleep 10; done;']
      - name: wait-for-prefixtree
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-prefixtree {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      - name: wait-for-database
        image: busybox
        command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-database {{ .Values.restPort }}; do echo waiting for services; sleep 10; done;' ]
      containers:
      - env:
        - name: RELEASE_NAME
          value: {{ .Release.Name }}
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: rabbitmqHost
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: rabbitmqPass
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: rabbitmqPort
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: rabbitmqUser
        - name: REST_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: restPort
        image: inspiregroup/artemis-mitigation:{{ .Values.systemVersion }}
        imagePullPolicy: Always
        name: mitigation
        resources: {}
        volumeMounts:
        - mountPath: /etc/artemis/logging.yaml
          name: mitigation-configmap
          subPath: logging.yaml
      restartPolicy: Always
      volumes:
      - configMap:
          name: {{ .Release.Name }}-volumes
        name: mitigation-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
