apiVersion: {{ template "artemis.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: pg-amqp-bridge
{{ include "artemis.labels" . | indent 4 }}
  name: pg-amqp-bridge
spec:
  selector:
    matchLabels:
      app: pg-amqp-bridge
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pg-amqp-bridge
    spec:
      initContainers:
      - name: wait-for-service
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z {{ .Values.rabbitmqHost }} {{ .Values.rabbitmqPort}}; do echo waiting for rabbitmq; sleep 10; done;']
      containers:
      - env:
        - name: AMQP_URI
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: rabbitmqUri
        - name: BRIDGE_CHANNELS
          value: events:amq.direct
        - name: POSTGRESQL_URI
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: dbUri
        image: subzerocloud/pg-amqp-bridge:0.0.6
        name: pg-amqp-bridge
        resources: {}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
