apiVersion: {{ template "artemis.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: postgrest
{{ include "artemis.labels" . | indent 4 }}
  name: postgrest
spec:
  selector:
    matchLabels:
      app: postgrest
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      initContainers:
      - name: wait-for-service
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z {{ .Values.dbHost }} {{ .Values.dbPort }}; do echo waiting for services; sleep 10; done;']
      containers:
      - env:
        - name: PGRST_DB_ANON_ROLE
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: dbUser
        - name: PGRST_DB_SCHEMA
          value: public
        - name: PGRST_DB_URI
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: dbUri
        image: postgrest/postgrest:v7.0.0
        name: postgrest
        resources: {}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
