apiVersion: {{ template "artemis.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-redis
{{ include "artemis.labels" . | indent 4 }}
  name: {{ .Release.Name }}-redis
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}-redis
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - image: redis:latest
        name: redis
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/etc/redis/redis.conf
          name: redis-configmap
          subPath: redis.conf
      restartPolicy: Always
      volumes:
      - configMap:
          name: {{ .Release.Name }}-volumes
        name: redis-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
