name: ci

on:
  push:
#    branches: [ master, pull_request ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        service: [ "autoignore" ] #, "autostarter", "configuration", "database", "detection", "fileobserver", "mitigation", "notifier", "prefixtree" ]
    steps:
      - uses: actions/checkout@v2
      - name: Print environment variables
        run: env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      #      - name: Login to DockerHub
      #        uses: docker/login-action@v1
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          # push: true
          context: ./backend-services/${{ matrix.service }}
          file: ./backend-services/${{ matrix.service }}/Dockerfile
          tags: inspiregroup/artemis-${{ matrix.service }}:latest # ${BUILD_TAG}
          cache-from: type=registry,ref=inspiregroup/artemis-${{ matrix.service }}:latest
          # type=registry,ref=inspiregroup/artemis-${{ matrix.service }}:${BUILD_TAG}
          cache-to: type=inline
