name: ci

on:
  push:
#    branches: [ master, pull_request ]

env:
  BUILD_TAG: $(if [ "${GITHUB_REF##*/}" == "master" ] && [ "${GITHUB_HEAD_REF}" == "" ]; then echo "latest"; else echo dev-PR${{github.event.number}}; fi)

jobs:
  build-backend:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        service: [ "autoignore", "autostarter" ] # , "configuration", "database", "detection", "fileobserver", "mitigation", "notifier", "prefixtree" ]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      #      - name: Login to DockerHub
      #        uses: docker/login-action@v1
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          #          push: true
          context: ./backend-services/${{ matrix.service }}
          file: ./Dockerfile
          tags: inspiregroup/${{ matrix.service }}:${BUILD_TAG}
          cache-from: |
            type=registry,ref=inspiregroup/${{ matrix.service }}:latest
            type=registry,ref=inspiregroup/${{ matrix.service }}:${BUILD_TAG}
          cache-to: type=inline
